#!/usr/bin/env bash
# perf.config.sh — project targets for the creo-perf harness. Sourced (bash)
# by every harness script after PERF_PROJECT_ROOT is set. Generated by
# `/creo perf init` for project "__PROJECT_ID__"; edit freely — it is yours.
# Reference: creo-perf skill, references/scenario-spec.md

PERF_PROJECT_ID="__PROJECT_ID__"

# ---------- HTTP targets ----------
# The backend reached DIRECTLY (bypasses any proxy) — API latency numbers.
PERF_API="http://localhost:8001"
# The same API THROUGH the edge proxy (nginx/Caddy/CDN) — compression, ETag and
# proxy overhead only exist here. Leave "" when there is no proxy layer.
PERF_PROXY="http://localhost:80/api"
# The served frontend (production build) — Lighthouse, asset probes, FE interactions.
PERF_WEB="http://localhost:80"
PERF_WEB_PATH="/"                                  # page Lighthouse loads
PERF_API_PATTERN="/api/"                           # regex: which requests count as API calls
# URLs that must answer before any capture starts.
PERF_PREFLIGHT_URLS=("$PERF_WEB/" "$PERF_API/docs")
# One representative API URL for the platform audit's edge-compression probe.
PERF_PROBE_URL="$PERF_API/items?page=0&page_size=100"

# ---------- database (PostgreSQL only in this version) ----------
PERF_DB_KIND="postgres"                            # postgres | none (skips EXPLAIN/schema/workload layers)
# psql invocation as an ARRAY. Examples:
#   (docker exec -i my-postgres psql -U user -d db -X -q)
#   (psql "postgresql://user:pass@localhost:5432/db" -X -q)
PERF_PSQL_CMD=(docker exec -i my-postgres psql -U user -d db -X -q)
PERF_DB_CONTAINER="my-postgres"                    # "" when not containerised (no restarts / log harvest)
PERF_API_CONTAINER="my-api"                        # "" if none; restarted after a DB restart (stale pools)
PERF_DB_TABLES=(items)                             # tables on the hot read path (schema audit)
PERF_DB_HOT_TABLE="items"                          # primary table; filters app-executed rows in scenario reports

# ---------- SQL runner generation (see sql-runners.py) ----------
# compile: sql-src/<runner>/<label>.sql hand-written statements (any stack)
# record:  sql-calls.py runs the real endpoint functions (SQLAlchemy/SQLModel apps)
# none:    no EXPLAIN sections
PERF_SQL_MODE="compile"
PERF_SQL_PYTHON="$PERF_PROJECT_ROOT/backend/.venv/bin/python"   # record mode interpreter

# ---------- frontend build (audit-fe.sh) ----------
PERF_APP_DIR="$PERF_PROJECT_ROOT/frontend"
PERF_SRC_DIR="$PERF_APP_DIR/src"
PERF_BUILD_CMD="npx --yes vite build --logLevel error"
PERF_DIST_DIR="$PERF_APP_DIR/dist"
PERF_BUNDLER="vite"                                # vite | other (composition breakdown is vite-only)
PERF_LIGHTHOUSE_RUNS=3

# ---------- backend source (audit-platform.sh) ----------
PERF_BACKEND_KIND="fastapi"                        # fastapi | node | other
PERF_BACKEND_DIR="$PERF_PROJECT_ROOT/backend"
PERF_ROUTES_GLOB="$PERF_BACKEND_DIR/app/route/*.py"   # fastapi: files holding @router.get/post handlers

# ---------- capture ordering (audit-all.sh) ----------
# Cache-churning scenarios (unbounded pages, huge payloads) last among
# scenarios; fe last of all (builds + Lighthouse load the machine).
PERF_ALL_ORDER=(platform schema s1 fe)

# ---------- hazards (echoed by preflight; also list them in creo-perf-__PROJECT_ID__.md) ----------
PERF_HAZARDS=(
  "never run docker compose down -v (wipes the seeded volume)"
  "never run ANALYZE mid-audit — planner-stats state is itself an observation"
)
