#!/usr/bin/env bash
# lib-harness.sh — bootstrap shared by every creo-perf harness script.
# NOT executable on its own; source it first thing. It resolves:
#   HARNESS_DIR      this extension's scripts/ directory
#   PROJECT_ROOT     the project being measured (PERF_PROJECT_ROOT or git toplevel)
#   EXT_DIR          $PROJECT_ROOT/.claude/skills/creo-perf  (project extension)
#   RESULTS          $EXT_DIR/results (override: PERF_RESULTS)
# then sources $EXT_DIR/perf.config.sh (generated by `/creo perf init`) and
# provides the helpers every capture script shares:
#   PSQL ARGS...            run psql against the project DB (PERF_PSQL_CMD)
#   pg_scalar SQL           scalar query
#   db_enabled              0/1 — is a DB layer configured (PERF_DB_KIND=postgres)
#   need_label "$@"         parse <label> [--runs N] [--force] into LABEL RUNS FORCE
#   claim_out SCENARIO      set OUT=$RESULTS/$LABEL/$SCENARIO, enforce immutability
#   preflight_http          every PERF_PREFLIGHT_URLS must answer
#   stamp                   GIT_HEAD + STAMP
#   mdsafe                  make text safe inside a markdown table cell
#   rebuild_dashboard       regenerate $RESULTS/dashboard.md
#   proxy_url URL           URL rewritten from PERF_API to PERF_PROXY ('' if no proxy)

HARNESS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HARNESS_COMMON="$HARNESS_DIR/common"
HARNESS_TEMPLATES="$(cd "$HARNESS_DIR/../templates" && pwd)"

PROJECT_ROOT="${PERF_PROJECT_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
export PERF_PROJECT_ROOT="$PROJECT_ROOT"
EXT_DIR="${PERF_EXT_DIR:-$PROJECT_ROOT/.claude/skills/creo-perf}"
CONFIG="$EXT_DIR/perf.config.sh"

if [[ -f "$CONFIG" ]]; then
  # shellcheck disable=SC1090
  source "$CONFIG"
elif [[ "${PERF_ALLOW_NO_CONFIG:-0}" != "1" ]]; then
  echo "ERROR: no perf.config.sh at $CONFIG — run '/creo perf init' (or init-project.sh) first" >&2
  exit 2
fi

RESULTS="${PERF_RESULTS:-$EXT_DIR/results}"
export PERF_RESULTS="$RESULTS"
PERF_API="${PERF_API:-}"
PERF_PROXY="${PERF_PROXY:-}"
PERF_WEB="${PERF_WEB:-}"
PERF_DB_KIND="${PERF_DB_KIND:-none}"
PERF_DB_HOT_TABLE="${PERF_DB_HOT_TABLE:-}"
PERF_DB_CONTAINER="${PERF_DB_CONTAINER:-}"
PERF_API_CONTAINER="${PERF_API_CONTAINER:-}"

db_enabled() { [[ "$PERF_DB_KIND" == "postgres" ]]; }

PSQL() {
  db_enabled || { echo "PSQL called but PERF_DB_KIND=$PERF_DB_KIND" >&2; return 1; }
  "${PERF_PSQL_CMD[@]}" "$@"
}
pg_scalar() { PSQL -t -A -c "$1" </dev/null; }

# pg_idx_info TABLE SQL-PREDICATE -> "name (size · am (expr)) + …" for matching
# indexes of TABLE. idx_scan is deliberately omitted: pg_stat counters are
# cumulative since the last reset, so they measure how much traffic a capture
# drove, not the effect of a fix (build-dashboard.py scrubs them too).
pg_idx_info() { # TABLE PREDICATE(over s = pg_stat_user_indexes)
  pg_scalar "SELECT COALESCE(string_agg(
      s.indexrelname || ' (' || pg_size_pretty(pg_relation_size(s.indexrelid))
        || ' · ' || regexp_replace(pg_get_indexdef(s.indexrelid), '^.* USING ', '') || ')',
      ' + ' ORDER BY s.indexrelname), 'none')
    FROM pg_stat_user_indexes s WHERE s.relname = '$1' AND ($2);"
}
pg_idx_named() { # TABLE PREDICATE -> first matching index name, else 'none'
  pg_scalar "SELECT COALESCE(min(s.indexrelname), 'none')
    FROM pg_stat_user_indexes s WHERE s.relname = '$1' AND ($2);"
}

need_label() { # "$@" -> LABEL RUNS FORCE EXTRA_ARGS
  LABEL="" RUNS="${RUNS:-10}" FORCE=0 EXTRA_ARGS=()
  while [[ $# -gt 0 ]]; do case "$1" in
    --label) LABEL="$2"; shift 2 ;;
    --runs) RUNS="$2"; shift 2 ;;
    --force) FORCE=1; shift ;;
    --*|-*) EXTRA_ARGS+=("$1"); shift ;;
    *) if [[ -z "$LABEL" ]]; then LABEL="$1"; shift; else echo "unexpected arg: $1 (label already '$LABEL')" >&2; exit 2; fi ;;
  esac; done
  [[ -n "$LABEL" ]] || { echo "usage: $0 <label> [--runs N] [--force]   (e.g. $0 before)" >&2; exit 2; }
}

claim_out() { # SCENARIO-ID -> OUT (immutable unless --force)
  OUT="$RESULTS/$LABEL/$1"
  if [[ -d "$OUT" && $FORCE -eq 0 ]]; then
    echo "ERROR: $OUT exists. Baselines are immutable — use a new label, or --force ONLY for a non-baseline capture." >&2
    exit 1
  fi
  mkdir -p "$OUT"
}

preflight_http() {
  local u
  for u in "${PERF_PREFLIGHT_URLS[@]:-}"; do
    [[ -n "$u" ]] || continue
    curl -sf -o /dev/null --max-time 5 "$u" || { echo "PREFLIGHT FAIL: $u not reachable (stack up?)" >&2; exit 1; }
  done
  if db_enabled; then
    pg_scalar "SELECT 1;" | grep -q 1 || { echo "PREFLIGHT FAIL: PERF_PSQL_CMD cannot reach the database" >&2; exit 1; }
  fi
}

stamp() {
  GIT_HEAD="$(git -C "$PROJECT_ROOT" rev-parse --short HEAD 2>/dev/null || echo nogit)"
  STAMP="$(date -u +%Y-%m-%dT%H:%MZ)"
}

mdsafe() { tr '|\t' '¦ '; }

proxy_url() { # URL -> same URL through the proxy, or '' when no proxy configured
  [[ -n "$PERF_PROXY" && "$1" == "$PERF_API"* ]] || { echo ""; return; }
  echo "$PERF_PROXY${1#"$PERF_API"}"
}

rebuild_dashboard() {
  PERF_RESULTS="$RESULTS" PERF_EXT_DIR="$EXT_DIR" python3 "$HARNESS_COMMON/build-dashboard.py" \
    || echo "WARN: dashboard rebuild failed" >&2
}

# container helpers — no-ops when the DB is not containerised
db_container_logs_since() { # ISO-UTC-STAMP
  [[ -n "$PERF_DB_CONTAINER" ]] || return 0
  docker logs --since "${1}Z" "$PERF_DB_CONTAINER" 2>&1
}
db_restart() {
  [[ -n "$PERF_DB_CONTAINER" ]] || { echo "   NOTE: PERF_DB_CONTAINER unset — restart postgres yourself, then press enter"; read -r; return 0; }
  docker restart "$PERF_DB_CONTAINER" >/dev/null
  echo -n "   waiting for postgres"
  local i
  for i in $(seq 1 60); do
    pg_scalar "SELECT 1;" 2>/dev/null | grep -q 1 && break
    echo -n "."; sleep 1
  done
  echo " up"
  pg_scalar "SELECT 1;" | grep -q 1 || { echo "FAIL: postgres did not come back" >&2; exit 1; }
  if [[ -n "$PERF_API_CONTAINER" ]]; then
    docker restart "$PERF_API_CONTAINER" >/dev/null && echo "   restarted $PERF_API_CONTAINER (stale pool connections after a DB restart)"
  fi
}
