#!/usr/bin/env bash
set -euo pipefail

# init-project.sh — scaffold the creo-perf project extension for the current
# repository. Mechanical part of `/creo perf init`: copies templates into
# .claude/skills/creo-perf/, writes a `perf` wrapper that resolves the harness,
# and adds the gitignore entries. The intelligent part (filling targets,
# proposing scenarios from the route code, writing SQL sources and the
# extension doc) is done by the skill after this runs.
#
# Usage: init-project.sh [--project-id ID] [--force] [--project-root DIR]
#   --project-id     default: project_id from .claude/project-config.md, else repo dir name
#   --force          overwrite existing template-derived files (never touches results/)

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HARNESS="$(cd "$DIR/.." && pwd)"
TPL="$HARNESS/templates"

PID="" FORCE=0 ROOT=""
while [[ $# -gt 0 ]]; do case "$1" in
  --project-id) PID="$2"; shift 2 ;;
  --project-root) ROOT="$2"; shift 2 ;;
  --force) FORCE=1; shift ;;
  *) echo "usage: $0 [--project-id ID] [--project-root DIR] [--force]" >&2; exit 2 ;;
esac; done

ROOT="${ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
EXT="$ROOT/.claude/skills/creo-perf"
if [[ -z "$PID" && -f "$ROOT/.claude/project-config.md" ]]; then
  PID=$(grep -iE '^\s*[-*]?\s*\**project_id\**\s*[:=]' "$ROOT/.claude/project-config.md" | head -1 | sed -E 's/.*[:=]\s*//; s/[`"'"'"' ]//g' || true)
fi
PID="${PID:-$(basename "$ROOT" | tr '[:upper:] ' '[:lower:]-')}"

echo "creo-perf init — project '$PID' at $ROOT"
echo "harness: $HARNESS"
mkdir -p "$EXT/scenarios" "$EXT/sql-src" "$EXT/sql" "$EXT/results"

put() { # TEMPLATE DEST [substitute]
  local src="$TPL/$1" dst="$EXT/$2"
  if [[ -f "$dst" && $FORCE -eq 0 ]]; then echo "  keep  $2 (exists; --force to overwrite)"; return; fi
  sed -e "s|__PROJECT_ID__|$PID|g" -e "s|__HARNESS__|$HARNESS|g" -e "s|__PROJECT_ROOT__|$ROOT|g" "$src" > "$dst"
  echo "  write $2"
}

put perf.config.sh perf.config.sh
put dashboard.json dashboard.json
put fe-interactions.json fe-interactions.json
put sql-calls.py sql-calls.py
put column-usage.tsv column-usage.tsv
put hypopg-candidates.tsv hypopg-candidates.tsv
put creo-perf-project.md "creo-perf-$PID.md"
put README.md README.md
if [[ ! -f "$EXT/scenarios/s1.sh" || $FORCE -eq 1 ]]; then
  sed -e "s|__ID__|s1|g" -e "s|__DESC__|user opens the main list page (page 1, default sort, no filters)|g" "$TPL/scenario.template.sh" > "$EXT/scenarios/s1.sh"
  echo "  write scenarios/s1.sh (example — edit URLs, add more scenarios)"
fi
cp "$TPL/scenario.template.sh" "$EXT/scenarios/.template.sh"

# wrapper: `.claude/skills/creo-perf/perf <script> [args]` -> harness script
cat > "$EXT/perf" <<EOF
#!/usr/bin/env bash
# creo-perf harness wrapper — generated by init-project.sh. Usage:
#   .claude/skills/creo-perf/perf preflight
#   .claude/skills/creo-perf/perf audit-all before
#   .claude/skills/creo-perf/perf audit-scenario s1 after-index
#   .claude/skills/creo-perf/perf audit-fe|audit-platform|audit-schema <label>
#   .claude/skills/creo-perf/perf workload-pre|workload-drive|workload-post <label>
#   .claude/skills/creo-perf/perf dashboard
set -euo pipefail
export PERF_PROJECT_ROOT="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")/../../.." && pwd)"
HARNESS="\${PERF_HARNESS:-$HARNESS}"
[[ -d "\$HARNESS/scripts" ]] || HARNESS="\$HOME/.claude/skills/creo-perf-harness"
[[ -d "\$HARNESS/scripts" ]] || { echo "creo-perf harness not found (set PERF_HARNESS or install extensions/perf-harness)" >&2; exit 1; }
cmd="\${1:-}"; shift || true
case "\$cmd" in
  dashboard) PERF_RESULTS="\${PERF_RESULTS:-\$PERF_PROJECT_ROOT/.claude/skills/creo-perf/results}" PERF_EXT_DIR="\$PERF_PROJECT_ROOT/.claude/skills/creo-perf" exec python3 "\$HARNESS/scripts/common/build-dashboard.py" ;;
  ""|-h|--help) sed -n '2,8p' "\$0"; ls "\$HARNESS/scripts/"*.sh | xargs -n1 basename | sed 's/\.sh\$//; s/^/  /' ;;
  *) [[ -x "\$HARNESS/scripts/\$cmd.sh" ]] || { echo "unknown command \$cmd" >&2; exit 2; }; exec "\$HARNESS/scripts/\$cmd.sh" "\$@" ;;
esac
EOF
chmod +x "$EXT/perf"
echo "  write perf (wrapper)"

# gitignore: raw captures are not committed; the dashboard is
GI="$ROOT/.gitignore"
if ! grep -qs 'creo-perf/results/\*' "$GI" 2>/dev/null; then
  { echo; cat "$TPL/gitignore.snippet"; } >> "$GI"
  echo "  append .gitignore (results/* except dashboard.md)"
fi

echo
echo "Scaffolded $EXT"
echo "Next:"
echo "  1. Fill perf.config.sh (targets, DB access, app dirs) and scenarios/*.sh (URLs, SQL runners)"
echo "  2. $EXT/perf preflight"
echo "  3. $EXT/perf audit-all before        # immutable baseline"
